#!/bin/bash
# TODO . config/config.var.sh

PRGM_NAME="runtest"

version=$(basename "$(cat config/last_version)")
log_fail_permission="740"
log_fail_path="logs/test_fails.logs"
log_runtest_path="logs/runtest.logs"
classes_dir="src/classes"
tests_dir="src/tests"
has_been_errors=0
compilation_errors=0
compilation_count=0
test_count=0

rm $log_fail_path 2> /dev/null
touch $log_fail_path
echo "#!/bin/bash" > $log_fail_path
chmod $log_fail_permission $log_fail_path > /dev/null
echo "$PRGM_NAME : New log file created with permission $log_fail_permission : $log_fail_path"

for i in $classes_dir/*/*.test.cpp
do
	fileName=$(basename $i)
	testName="${fileName%%.*}"
	echo "$testName : Starting to process ..."
	ls $classes_dir/*-$testName.test > /dev/null 2> /dev/null
	if [ $? -eq -1 ]; then
		echo "$testName : Automatically added as new test"
		git add $i > /dev/null 2>&1
		git commit -m "Added new test : $testName" > /dev/null 2> /dev/null
		git push > /dev/null 2>&1
		echo "[$(date)] => Added new test $testName to $tests_dir" >> logs/general.logs
	fi
	rm $tests_dir/$version-$testName.test > /dev/null 2> /dev/null
	echo "$testName : Compilation to $tests_dir/$version-$testName.test ..."
	compilation_count=$(($compilation_count+1))
	g++ $i $(cat "${i%%.*}.test.dependencies") -o "$tests_dir/$version-$testName.test" #> /dev/null 2> /dev/null
	if [ ! $? -eq 0 ]; then
		echo "$testName : Compilation failed."
		echo "[$(date)] -- $testName : Compilation failed." >> $log_runtest_path
		echo "g++ $i -o $tests_dir/$version-$testName.test" >> $log_fail_path
		compilation_errors=$(($compilation_errors+1))
	else
		echo "$testName : Compilation success."
		echo "[$(date)] -- $testName : Compilation success." >> $log_runtest_path
		chmod +x $tests_dir/$version-$testName.test > /dev/null
		echo -n "$testName : "
		$tests_dir/$version-$testName.test
		err=$?	
		if [ $err -eq 0 ]; then
			echo "$testName : Run test success."
			echo "[$(date)] ++ $testName : Run test success." >> $log_runtest_path
		else
			echo "$testName : Run test failed. ($fileName returns $err)"
			echo "[$(date)] -- $testName : Run test failed. ($fileName returns $err)" >> $log_runtest_path
			echo "g++ $i -o $tests_dir/$version-$testName.test" >> $log_fail_path
			echo "$tests_dir/$version-$testName.test" >> $log_fail_path
			has_been_errors=$(($has_been_errors+1))
		fi
		test_count=$(($test_count+1))
	fi
done

if [ $compilation_errors -gt 0 ]; then
	echo -n "$PRGM_NAME : $compilation_errors/$compilation_count tests have failed compiling. "
else
	echo -n "$PRGM_NAME : All tests have been executed : "
fi

if [ $has_been_errors -gt 0 ]; then
	echo "$has_been_errors/$test_count tests have reported errors. Please see $log_fail_path to solve them."
	exit -1
else
	echo "$test_count/$test_count tests performed without errors."
	exit 0
fi
